# The URL the site will be built for
base_url = "https://www.amateurguitar.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "juice"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
juice_logo_name = "Amateur Guitar"
juice_logo_path = "juice.svg"
repository_url = "https://github.com/amateurguitar/feedbacks"
